@startuml
entity User {
  * id : UUID
  * name : String
}

entity Device {
  * id : UUID
}

entity TargetTemperature {
    * deviceId: UUID
    * temperature: Number
}

entity Telemetry {
    * deviceId: UUID
    * temperature: Number
}
entity Location {
  * id : UUID
  * deviceId: UUID
}

User --> Location : generates
Location --> Device: contains
User --> TargetTemperature: generates
TargetTemperature --> Device: has
Device --> Telemetry: contains
@enduml